language: ruby

cache: bundler

before_install:
- gem install bundler -v '2.0.1'

jobs:
  include:
    - stage: "testing time"
      script:
        - bundle exec rspec spec
        - bundle exec rspec spec/integrate/configs_spec.rb --tag integration_configs
        - bundle exec rspec spec/integrate/matrix_spec.rb --tag integration_matrix

    - stage: ":ship: it to quay.io"
      language: ruby
      cache:
        bundler: false
      before_install: skip
      install: skip
      script: make ship
      if: type = cron OR commit_message =~ /ship:docker/ OR env(SHIP_DOCKER) = true
